# Generated by Django 4.0.5 on 2025-11-10 02:03

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=store.models.get_file_path)),
                ('description', models.TextField(max_length=100)),
                ('status', models.BooleanField(default=False, help_text='0 = default, 1 = Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0 = default, 1 = Trending')),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_keyword', models.CharField(max_length=40)),
                ('meta_description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(blank=True, upload_to=store.models.get_file_path)),
                ('small_description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0 = default, 1 = Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0 = default, 1 = Trending')),
                ('tag', models.CharField(max_length=20)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_keyword', models.CharField(max_length=40)),
                ('meta_description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
