# Generated by Django 4.0.5 on 2025-11-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_profile_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Out of shipping', 'Out of shipping'), ('Pending', 'Pending')], default='pending', max_length=100),
        ),
    ]
