# Generated by Django 4.0.5 on 2025-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out of shipping', 'Out of shipping'), ('Completed', 'Completed')], default='pending', max_length=100),
        ),
    ]
